### ISSUE TITLE
Where do I get credentials for configuration

### ISSUE THREAD

**Issue by alonisser** [yaron2/aks-autoscaler#1]
Thanks for this project! 
In the readme:

>>APP_ID - A Service Principal ID of an AAD app that has contributor permissions for the AKS cluster
>>PASSWORD - The password of the AD app
>>TENANT_ID - Your Azure subscription's TenantID

Where do I get those credentials from in azure aks?

**Comment by yaron2** [comment]
Hi,

Login to azure cli and then create a Service Principal:

az ad sp create-for-rbac --name aks-autoscaler -o table

It will spit out the configurations for you.
